#!/bin/sh
#
# Start App....
#

start() {
      	printf "Starting /etc/init.d/script/startup.sh : "
	cd /etc/init.d/script/
	. startup.sh
	cd -
	echo "OK"
}

stop() {
	printf "Stopping NCS: "
	killall ncs	
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
