var language= 
{
  "label_title": "IP NETWORK INTERCOM SYSTEM",
  "label_login": "Login",
  "label_username": "Username",
  "label_password": "Password",
  "label_null": "Please input ",
  "label_loginfail": "Login Failed: username or password incorrect!",
  "label_sysinfo": "System Information",
  "label_terminal_id": "Terminal ID",
  "label_terminal_ip": "Terminal IP",
  "label_netmask": "Subnet Mask",
  "label_gateway": "Gateway",
  "label_macaddr": "MAC Address",
  "label_refresh": "Refresh",
  "label_basic": "--- Basic Settings ---",
  "label_network": "Net options",
  "label_dns1": "DNS1(Optional)",
  "label_dns2": "DNS2(Optional)",
  "label_save": "Save",
  "label_rebootconfirm": "Rebooting the device?",
  "label_saveconfirm": "Save ok，reboot please！",
  "label_invalid": " is not a valid ",
  "label_ip": " IP",
  "label_port": " Port",
  "label_server": "Server options",
  "label_local_port": "Local Port",
  "label_server1": "Primary Server",
  "label_server2": "Secondary Server",
  "label_version_server": "Version Server",
  "label_ftp_server": "FTP Server",
  "label_ftp_username": "FTP Username",
  "label_ftp_passwd": "FTP Password",
  "label_login_intvl": "Login Interval(s)",
  "label_sip": "SIP options",
  "label_enable": "Enable",
  "label_disable": "Disable",
  "label_sip_localport":"Net Port",
  "label_sip_server": "SIP Server",
  "label_sip_username": "Account",
  "label_sip_passwd": "Password",
  "label_sip_audioport": "Audio port",
  "label_sip_videoport": "Video port",
  "label_sip_caller": "SIP Caller",
  "label_sip_target1": "Phone Target1",
  "label_sip_target2": "Phone Target2",
  "label_audio": "Audio options",
  "label_talkin": "Talking Input Select",
  "label_mic": "Mic",
  "label_line": "Line",
  "label_recorder": "Recorder",
  "label_talkout": "Talking Output Select",
  "label_speaker": "Speaker",
  "label_talkin_vol": "Talking Input Volume",
  "label_talkout_vol": "Talking Output Volume",
  "label_ring_vol": "Talking Ring Volume",
  "label_broadcast": "Broadcast Output Select",
  "label_broadcast_vol": "Broadcast Volume",
  "label_monitor": "Monitor Input Select",
  "label_monitor_vol": "Monitor Volume",
  "label_talk": "Talk options",
  "label_autoanswer": "Auto answer",
  "label_hangup": "Hangup",
  "label_echo": "Echo cancellation",
  "label_environment": "Pickup distance",
  "label_near": "Near",
  "label_middle": "Middle",
  "label_far": "Far",
  "label_talkend": "Close All video after hangup",
  "label_offline": "Offline Talk",
  "label_left": "Offline Target1",
  "label_right": "Offline Target2",
  "label_alarm": "Alarm options",
  "label_alarm_in1": "Alarm Input1 trigger mode",
  "label_alarm_in2": "Alarm Input2 trigger mode",
  "label_short_out_mode1": "Alarm Output1 Init Status",
  "label_short_out_mode2": "Alarm Output1 Init Status",
  "label_open_always": "Always open",
  "label_closed_always": "Always close",
  "label_open": "Open circuit alarm",
  "label_closed": "Closed circuit alarm",
  "label_dismantle": "Dismantle alarm",
  "label_noise": "Noise alarm",
  "label_noise_vol": "Noise alarm Trigger Volume",
  "label_noise_time": "Noise alarm Trigger Time(s)",
  "label_systool": "--- System Tools ---",
  "label_passwd": "Password Setting",
  "label_usrname_origin": "Original username",
  "label_passwd_origin": "Original password",
  "label_usrname_new": "New username",
  "label_passwd_new": "New password",
  "label_passwd_confirm": "Password Confirm",
  "label_passwd_error": "The password and the confirmation do not match!",
  "label_passwd_success": "Change username and password success!",
  "label_passwd_fail": "Change username and password failed: authentication failed!",
  "label_reset": "Clear",
  "label_language_setting": "Language Setting",
  "label_language": "Language",
  "label_reboot": "Reboot",
  "label_rebootinfo": "Click button to reboot the device. ",
  "label_factory": "Factory reset",
  "label_factory_info": "Restore last correct settings or factory settings when the device fails.",
  "label_last": "Last correct setting",
  "label_factory_confirm": "Restoring factory ,reboot please.",
  "label_last_confirm": "Restoring last setting,reboot please.",
  "label_firmware": "Update firmware",
  "label_recovery": "Enter recovery mode",
  "label_firmware_version": "Firmware version",
  "label_path": "Path",
  "label_notice": "Notice：Keep power on while updating otherwise updating may fail, update process will take 60 seconds，the device will automatically reboot when update complete.",
  "label_update": "Update",
  "label_syslog": "System logs",
  "label_index": "Index",
  "label_content": "Log content",
  "label_helpinfo": "Help",
	//-----------------jack 8523D add
	"label_status": "status change alarm",
	"label_priority": "Priority ",
	"label_alarm_enmergecy": "enmergency al",
	"label_alarm_move": "moving alarm",
	"label_alarm_door1": "door1 alarm",
	"label_alarm_door2": "door2 alarm",
	"status_change_alarm": "status change",
	"label_alarm_talk": "talking alarm",
	"label_alarm_extern_in1": "extern in1",
	"label_alarm_extern_in2": "extern in2",
	"label_priority": "Priority",
	"label_video_onvif": "ONVIF",
	"label_video_wdr": "WDR",
	"label_video_resolution": "video resolution",
	"label_pannel_speaker_testing": "pannel speaker testing",
};